spring.application.name=BlackJack


server.port=8080


spring.thymeleaf.cache=false


spring.datasource.url=jdbc:mysql://localhost:3307/blackjack_database

spring.datasource.username=blackjack_user

spring.datasource.password=blackjack_password


spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true


spring.flyway.enabled=true

spring.flyway.locations=classpath:db/migration

logging.level.org.springframework.security=DEBUG
logging.level.blackjack=DEBUG